import Head from 'next/head'
import Nabvar from './components/navbar/idex'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sky Eleven Tradin Solutions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nabvar/>
    </>
  )
}
